### ISSUE TITLE
Add async/await api compatible with Swift 5.5

### ISSUE THREAD

**Issue by pgorzelany** [blockfrost/blockfrost-swift#1]
Hi,

With Swift 5.5 Apple has introduced a new concurrency paradigm:
https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html

I propose adding an additional api to this library that would add async/await support.

**Comment by ph4r05** [comment]
@pgorzelany correct, we are aware of integration Async/Await to Swift. 

However, as Swift 5.5 was not globally available at the time of writing this SDK, we decided not to integrate it. SDK uses basic Swift.Result and completion handler logic, so it can be easily ported to async/await in the app code should you need it. 

Personally I would wait a while to make sure Swift 5.5 is widely adopted, before requiring minimal 5.5 version in the SDK. E.g., not all projects (or their dependencies) migrated to 5.5, so it would be impossible for them to use 5.5-version of this SDK for now. 
Recently I had issues with a project requiring https://github.com/yannickl/AwaitKit/issues/58 as a dependency. Switching to 5.5 does not work due to `await` keyword conflict, so migrating to 5.5 is nontrivial. 

Later we can think about adding async/await method versions (completion-style methods will be preserved).
Or we can add extension shim, i.e., a new package, for async/await, preserving original SDK Swift minimal version, adding extension methods with async/await.

**Comment by afern247** [comment]
I also think this would be a great feature +1. Currently using Async/Await.

Since cardano mainnet was released not too long ago I don't think many real projects have developed yet, so they can easily adopt the new Swift 5.5 features.

**Comment by Micrograx** [comment]
+1 to adding async/await support. 

I hope that development of the SDK continues at some point and integrates the modern language features.

**Comment by ph4r05** [comment]
PR #6 will be merged soon. If you have a minute, could you check it pls if it meets your requirements? Thanks!

**Comment by Micrograx** [comment]
PR looks awesome! Using async/await with the SDK will be so easy. Thanks for your work.

**Comment by ph4r05** [comment]
Thanks @Micrograx! You can give it a try, 1.0.0 was released just now.
